# Generated by Django 4.1.7 on 2023-03-26 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_detailed_description'),
        ('app', '0011_package_package_airport_alter_package_date'),
    ]

    operations = [
    ]
