# Generated by Django 4.1.7 on 2023-03-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_merge_20230326_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='package_airport',
        ),
        migrations.AlterField(
            model_name='package',
            name='date',
            field=models.DateField(),
        ),
    ]
