# Generated by Django 4.1.7 on 2023-03-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_package_package_airport_alter_package_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_airport',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
